import { text } from 'stream/iter';
import type { HistoryEntry, Settings } from './types';

export const defaultSettings: Settings = {
  llmModel: '',
  whisperModel: '',
  whisperCudaRuntimeVersion: 'cuda-12',
  whisperLanguage: 'auto',
  whisperQualityMode: 'balanced',
  llmCudaRuntimeVersion: 'cuda-13',
  llmMaxTokensMode: 'auto',
  llmMaxTokens: 160,
  llmContextSize: 4096,
  llmTemperature: 0.1,
correctionPrompt: [
  'You are a correction and formatting engine for dictated text.',
  '',
  'Rules, in priority order:',
  '- Return only the corrected text.',
  '- Keep the same language as the input.',
  '- Keep the same meaning, tone, level of formality, vocabulary, and technical terms.',
  '- Fix obvious dictation and formatting problems: stuck words, missing spaces, missing sentence breaks, missing paragraphs, repeated phrases, false starts, and stray fragments.',
  '- Correct spelling, grammar, agreements, spacing, sentence starts, and simple punctuation.',
  '- Use readable paragraphs for long text or topic changes.',
  '- Use simple punctuation: commas, periods, question marks, colons, and line breaks.',
  '- Preserve existing formatting when present, including Markdown headings, bullet markers, numbering, quotes, inline code, code blocks, and line breaks.',
  '- If Markdown exists in the input, keep the same Markdown structure and correct only the surrounding text.',
  '- If Markdown does not exist in the input, do not add Markdown formatting.',
  '- Do not add new headings, bullets, labels, backticks, quotes, brackets, bold, italic, or code formatting.',
  '- Keep IT jargon, UI terms, product names, code, commands, variables, paths, logs, quoted errors, and mixed English terms unchanged.',
  '- Do not translate technical terms.',
  '- Do not change lowercase technical or UI terms to title case.',
  '- Do not rewrite clear sentences just to improve style.',
  '- Do not make the text more formal, elegant, literary, or marketing-like.',
  '- Do not add facts, explanations, summaries, or details.',
  '',
  'Text to correct:',
  '',
].join('\n'),
  pasteAfterDictation: false,
  pasteAfterImprovement: false,
  improveSelectedText: false,
  microphoneDeviceId: '',
  microphoneDeviceLabel: '',
  microphoneEchoCancellation: true,
  microphoneNoiseSuppression: true,
  microphoneAutoGainControl: true,
  silenceSensitivity: 'normal',
  maxHistoryItems: 100,
  hotkeys: {
    speak: 'Alt+A',
    improveText: 'Alt+Z',
    transcript: 'Alt+E',
  },
};

export const sampleHistory: HistoryEntry[] = [];
