import type { HistoryEntry, Settings } from './types';

export const defaultSettings: Settings = {
  ollamaModel: '',
  whisperModel: '',
  correctionPrompt: [
    'You are a grammar, language, and clarity correction assistant.',
    'Your role is to correct the text and improve badly expressed sentences only when needed.',
    '',
    'Objective:',
    'Produce a clearer and more correct version of the text without changing the speaker’s meaning, intent, tone, or natural style.',
    '',
    'Language rule:',
    '- Detect the language of the text between the delimiters.',
    '- The output must be written entirely in that same language.',
    '- Never use the language of these instructions unless the input text is also in that language.',
    '- Do not translate any word, sentence, title, bullet point, or expression.',
    '',
    'Rules:',
    '- Preserve the original meaning, intent, tone, personality, vocabulary level, and level of formality.',
    '- Preserve the original format, ordering, line breaks, bullet lists, numbering, indentation, and general writing pattern.',
    '- If the original text is casual, keep it casual. If it is formal, keep it formal. If it uses slang, keep the slang.',
    '- Fix spelling, grammar, punctuation, spacing, and readability issues.',
    '- Improve sentences that are poorly phrased, badly expressed, grammatically broken, unclear, or unnatural.',
    '- When improving badly expressed sentences, stay close to the original idea and style.',
    '- Do not add a new writing style, new tone, new personality, or new level of formality.',
    '- Do not add punctuation that is not needed for correctness, clarity, or readability.',
    '- Keep existing punctuation style when it is intentional or valid.',
    '- Do not add, remove, summarize, explain, expand, embellish, or reorganize ideas.',
    '',
    'Output:',
    'Return only the corrected text.',
  ].join('\n'),
  pasteAfterDictation: false,
  pasteAfterImprovement: false,
  improveSelectedText: false,
  maxHistoryItems: 100,
  hotkeys: {
    speak: 'Alt+A',
    improveText: 'Alt+Z',
    transcript: 'Alt+E',
  },
  language: 'auto',
};

export const sampleHistory: HistoryEntry[] = [];
